### ISSUE TITLE
refactoring ToDo checklist

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/NASA-COG#240]
- [x] expand MAX31855 SensorConfig class such that the SensorConfig abstract class allows for definition through SensorConfig &config the pin definitions of the SPI bus used by the MAX31855 thermocouples, as opposed to how they are now hard defined with #define statements. 
- [x] need to refactor machine_core_def.h and move ODECS defines into a HAL similar to stage2_HAL
- [x] refactor platformio.ini such that we can fully isolate libraries and defines when not in use. for example, onewire isn't used in stage2_heater, but it has to be included because of all the unused headers and c file defines
- [x] Add in MAX31855 error checking into the readTemperature function to verify that the thermocouple amp is still operating as expected.

**Comment by RobertLRead** [comment]
@LokiMetaSmith I think this is irrelevant now, correct?

**Comment by LokiMetaSmith** [comment]
Correct
